app/main/forms.py

from flask_wtf import Form
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(Form):
    username = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

db = SQLAlchemy()
bootstrap = Bootstrap()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.index'

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)
	
	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)
	
	# attach routes and custom error pages here



	from app.main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	
	from app.auth import auth
	app.register_blueprint(auth)
	
	from app.archive import archive
	app.register_blueprint(archive)


	return app

app/archive/__init__.py
from flask import Blueprint

archive = Blueprint('archive', __name__,template_folder='../templates/archive')

from . import controllers, errors

app/archive/controllers.py
from flask import render_template, session, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash

from . import archive
#from .models import db, User
#from .forms import SignupForm
from flask_login import login_user, login_required, logout_user
from .. import login_manager
import os, shutil
#import pandas as pd

#APP_ROOT = os.path.dirname(os.path.abspath(__file__))
#APP_STATIC = os.path.join(app_instance_path,'static')


@archive.route('/archive', methods=['GET','POST'])
@login_required
def filelist():
	
	if request.method == 'POST':
		flist=request.form.getlist("check")
		print(flist)
		for file in flist:
			src = os.path.join("X:","DCCM Scans",file)
			filename = request.form.get("filename") 
			dst = os.path.join("X:","NPP Docs","NPP",filename)
			os.mkdir(dst)
			dst = os.path.join(dst,filename + ".pdf")
			shutil.copyfile(src, dst)
			os.remove(src)
	path = os.path.join("X:","DCCM Scans")
	lst = os.listdir(path)
	return render_template('archive.html',lst=lst,path=path)

#@archive.route('/transfer')
#def transfer():
	#filenames=request.form.getlist('check')
	#print(filenames)
	#return redirect(url_for('archive.archive'))

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__,template_folder='../templates/main')

from . import controllers, errors

app/main/controllers.py
from flask import render_template, session, redirect, url_for, request
from werkzeug.security import generate_password_hash, check_password_hash

from . import main
from .forms import LoginForm
from flask_login import login_required
from sklearn import datasets
import requests
import os
#from .models import db, User

@main.route('/')
def index():
	#return '<h1>Salam!</h1>'
	form = LoginForm()
	return render_template('index.html', form = form)

#@main.route('/login', methods=['POST'])
#def login():
	#name = request.form['username']
	#pwd = request.form['password']
	#user=User.query.filter_by(username=name).first()
	#if check_password_hash(user.password,pwd):
		#return render_template('login.html',user=user,pwd=1)
	#else:
		#return render_template('login.html',user=user,pwd=0)
@main.route('/model')
@login_required
def model():	
	digits = datasets.load_digits()
	dt = digits.data[1620:1625]
	url = 'http://localhost:5001/api'
	r = requests.post(url,json={'exp':dt.tolist()})
	#print(r.json())
	return render_template('model.html', a = r.json())

@main.route('/welcome')
def welcome():
    return render_template('welcome.html')

#@main.route('/archive', methods=['GET','POST'])
#def archive():
	#lst = os.listdir('X:\DCCM Scans\\')
	#return render_template('archive.html',lst=lst)

main.py
import os
from app import create_app

app = create_app(os.getenv('FLASK_CONFIG') or 'default')

if __name__ == '__main__':
	app.run()

app/templates/archive/archive.html


{% extends "base.html" %}
{% block title %}Archive Section{% endblock %}



{% block content %}
<div class="container">
	  <form action="{{url_for('archive.filelist')}}" method='POST'>
			{% for item in lst: %}
			<div><label> <input type="checkbox" name="check" value="{{item}}"> {{item}}</label> </div>
			{%endfor%}
			<input type="textbox" name="filename">
			<input type="submit" value="Archive">
	  </form>
</div>		  

{% endblock %}

app/templates/base.html
<!DOCTYPE html> 
<html>
<head> 
	
	<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" /> 
	<meta charset="utf-8" /> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<link href="{{url_for('static',filename='css/bootstrap.css')}}" rel="stylesheet" type="text/css" /> 
	{% block head %}
	<title>{% block title %}{% endblock %} - Flask Application</title>
	{% endblock %}
</head>

	<body> 
	<div class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">Flasky</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a href="/">Home</a></li>
					<li><a href="/signup">Sign Up</a></li>
					<li><a href="/logout">Logout</a></li>
				</ul>
			</div>
		</div>
	</div>	
	<!-- document code goes here --> 
	{% block content %}
	{% endblock %}	
	</body> 
	<script src="{{url_for('static',filename='js/jquery.js')}}" type="text/javascript"></script> 
	<script src="{{url_for('static',filename='js/bootstrap.js')}}" type="text/javascript"></script> 
</html>

app/templates/main/index.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock %}



{% block content %}
<div class="container">
<form action="{{url_for('auth.login')}}" method='POST'>
Name: {{ form.username() }}
Password:{{ form.password() }}
{{ form.submit() }}
</form>
<br>

<a href="{{ url_for('auth.signup') }}" class="btn
btn-primary btn-block">Sign Up</a>
</div>
{% endblock %}

app/templates/main/login_.html
{% if pwd == 1 %}
User Authenticated! {{user.password}}

{{ current_user.username }}


{% else%}
Sorry! User not Authenticated!
{%endif%}

app/templates/main/model.html
<h2> Welcome User</h2>


{{a}}


app/templates/main/user.html
{% if pwd == 1 %}
<h1>{{ pwd|capitalize}} </h1>User Authenticated! 
{% else%}
Sorry! User not Authenticated!{{ user.password}}
{%endif%}

app/templates/main/welcome.html
<h2> Welcome User</h2>